// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExpressionType } from "./ExpressionType";
import type { InterpretationCondition } from "./InterpretationCondition";
import type { InterpretedType } from "./InterpretedType";

export type DisplayInterpretation = { condition: InterpretationCondition, expressionType: ExpressionType, expressionPrecedence: number, outputType: InterpretedType, };