// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayTransformationLatticeLink } from "./DisplayTransformationLatticeLink";
import type { DisplayTransformationLatticeNode } from "./DisplayTransformationLatticeNode";

export type DisplayTransformationLattice = { nodes: Array<DisplayTransformationLatticeNode>, links: Array<DisplayTransformationLatticeLink>, };