// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisplayProvenance = { "kind": "hypothesis" } | { "kind": "derived" } & [number, number, Array<Array<number>>];