// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GeneratedTypeCondition } from "./GeneratedTypeCondition";
import type { Type } from "./Type";

export type DisplayGeneratedType = { condition: GeneratedTypeCondition, parents: Array<Type>, };