// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DisplayGeneratedType } from "./DisplayGeneratedType";
import type { DisplayInterpretation } from "./DisplayInterpretation";
import type { DisplayProvenance } from "./DisplayProvenance";
import type { DisplayTypeHierarchyNode } from "./DisplayTypeHierarchyNode";

export type DisplayWorkspace = { types: Array<DisplayTypeHierarchyNode>, generatedTypes: Array<DisplayGeneratedType>, interpretations: Array<DisplayInterpretation>, statements: Array<string>, transformations: Array<string>, provenance: Array<DisplayProvenance>, };