// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DerivedDisplayProvenance } from "./DerivedDisplayProvenance";

export type DisplayProvenance = { "kind": "hypothesis" } | { "kind": "derived" } & DerivedDisplayProvenance;