// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DisplaySymbolNode = { interpretedString: string, types: Array<[string, string]>, fromStatement: string | null, fromTransformation: string | null, };