// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Token } from "./Token";

export type ExpressionType = { "kind": "Singleton" } | { "kind": "Prefix" } | { "kind": "Infix" } | { "kind": "Postfix" } | { "kind": "Outfix", "token": Token } | { "kind": "Functional" };