// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Token } from "./Token";

export type ExpressionType = { "kind": "singleton" } | { "kind": "prefix" } | { "kind": "infix" } | { "kind": "postfix" } | { "kind": "outfix", "token": Token } | { "kind": "functional" };