// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneratedTypeCondition = { "kind": "isInteger" } | { "kind": "isNumeric" } | { "kind": "satisfiesRegex", "value": string };