// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Type } from "./Type";

export type InterpretedType = { "kind": "PassThrough" } | { "kind": "Delimiter" } | { "kind": "SameAsValue" } | { "kind": "Type", "type": Type };