// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Token } from "./Token";

export type InterpretationCondition = { "kind": "Matches", "token": Token } | { "kind": "IsObject" } | { "kind": "IsInteger" } | { "kind": "IsNumeric" };