// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Type = { "kind": "object" } | { "kind": "delimiter" } | { "kind": "join" } | { "kind": "namedType", "value": string };